### ISSUE TITLE
Image file compatibility.

### ISSUE THREAD

**Issue by gameofyou** [jeremyjh/ESP32_TFT_library#12]
I had a rather frustrating time getting the library working with my program, I for a while could not figure out what I was doing wrong, until I looked at the exact format of the pictures. While I don't actually think this is something that is worth fixing in the library, as producing compatible files is very easy, it is something that could save alot It would seem that the BMP and the JPG library only support some versions of these files.

BMP does not support "Color space information", including it will result in the file not working, the command "file" can so the difference bmps with color space information are newer Windows95/NT4 format.

bad.bmp:  PC bitmap, Windows 95/NT4 and newer format, 240 x 135 x 24
good.bmp: PC bitmap, Windows 3.x format, 240 x 135 x 24

With jpg files the key thing is to not use "progressive" mode.
bad.jpg:  JPEG image data, JFIF standard 1.01, resolution (DPI), density 72x72, segment length 16, progressive, precision 8, 240x135, frames 3
good.jpg: JPEG image data, JFIF standard 1.01, resolution (DPI), density 72x72, segment length 16, baseline, precision 8, 240x135, frames 3

Sadly GIMP saves files by default in  an unsupported format.

**Comment by jeremyjh** [comment]
I'm no longer maintaing this but I'd merge an update to the README.

**Comment by ksh1ng** [comment]
[gameofyou](https://github.com/gameofyou) Please use **"esptool.py write_flash <CONFIG_SPIFFS_BASE_ADD> <(SPIFFS_IMAGE_COMPONENT_PATH)>/spiffs_image.img"** in  ESP-IDF CMD
