### ISSUE TITLE
Some functions take non-const char*

### ISSUE THREAD

**Issue by mlepage-google** [jeremyjh/ESP32_TFT_library#16]
In tft.c, some functions take non-const char* as argument, when they should take const char*.

This makes it fairly annoying to call from C++, where without a const_cast, it will produce compiler warnings.

Some of the functions do take const char*, so they just all need to do so appropriately (which I'm guessing is all of them, as they shouldn't really be altering the input string).

**Comment by jeremyjh** [comment]
Fixed in #21 right?

**Comment by jeremyjh** [comment]
Doh sorry, this is talking about function arguments not local declarations.

**Comment by mlepage-google** [comment]
Correct. I think I fixed most in #17 but only in tft.c/.h and there are other files. Also it would be good if you could double-check that I didn't miss any, as I was mostly concerned with the ones I was actively using (so I could be sure it still built/worked properly after changing).

**Comment by jeremyjh** [comment]
Closing all open issues as I'm no longer maintaining this library, I've updated the README to reflect it.
