### ISSUE TITLE
spiffs create / flash with latest toolchain?

### ISSUE THREAD

**Issue by samsam4** [jeremyjh/ESP32_TFT_library#24]
Could you provide, please, some alternatives to  create and flash spiffs image used in this project
ESPPORT=<PORT> make copyfs
make makefs
ESPPORT=<PORT> make flashfs
as 'make' is no more available in current toolchain that is based on 'cmake'?
 
Thanks

**Comment by jeremyjh** [comment]
I'm no longer maintaining this fork, sorry. I've updated the README to let people know. I see make component files even in master of idf, I think you could still also have a Makefile in your project. I continued using make for these tasks even though I used CMAKE for builds but I can't even run a local build currently and can't offer further advice.
