### ISSUE TITLE
Touch function not working

### ISSUE THREAD

**Issue by eddeyonline** [jeremyjh/ESP32_TFT_library#5]
Hello,
I love what you've done with the library! The graphics are working great on my ESP32 Dev Kit V1 connected to an Ebay ILI9341 320x240 LCD with XPT2046 touch controller. However, the touch demo doesn't seem to be working at all. I know the hardware functions because it works perfectly with littlevgl/lv_port_esp32
I've wired as follows:
Breakout --> ESP32
VCC - 3v
GND - GND
CS - 5
RESET - 4
DC - 26
SDI(MOSI) - 23
SCK - 18
LED - VIN
SD0(MISO) - 19
T_CLK - 18
T_CS - 25
T_DIN - 23
T_DO - 19
T_IRQ - NOT CONNECTED

Note that MISO, MOSI and CLK lines are shared between the display and the touchscreen, however the CS lines are different.
When the touch screen was functioning with LittleVGL the touch interupt pin was in use, however there don't seem to be any instructions to use this pin with the ESP32_TFT_Library.
Any advice on getting the touchscreen to function would be much appreciated!
Thanks in advance,
Philip

**Comment by krzysiekzk** [comment]
Hello, 
I have the same problem, 
I run this library on the LCD 480x320 and LCD works great but touch dores not respond. In demo on LCD appears "Touch to draw" but dores not respond to touch. 
Did you solve your problem?

**Comment by eddeyonline** [comment]
No, I'm afraid I didn't solve it. I switched to the lvgl port, which has
its own issues but at least has working touch.
https://github.com/lvgl/lv_port_esp32

**Comment by jeremyjh** [comment]
Sorry I'd like to help but I do not have a touch controller to test with.

**Comment by jeremyjh** [comment]
Closing as I'm no longer maintaining this library.
