### ISSUE TITLE
compile error: the comparison will always evaluate as 'true"

### ISSUE THREAD

**Issue by Franciscopcosta** [jeremyjh/ESP32_TFT_library#6]
**I get this when trying to compile the example. Can you help me Jeremy? Thanks in advance. :)**

/home/fcosta/esp/esp-idf/components/heap/heap_caps_init.c: In function 'heap_caps_add_region_with_caps':
/home/fcosta/esp/esp-idf/components/heap/heap_caps_init.c:230:44: error: the comparison will always evaluate as 'true' for the address of 'registered_heaps_write_lock' will never be NULL [-Werror=address]
     MULTI_HEAP_LOCK(&registered_heaps_write_lock);
                                            ^~
/home/fcosta/esp/esp-idf/components/heap/heap_caps_init.c:232:45: error: the comparison will always evaluate as 'true' for the address of 'registered_heaps_write_lock' will never be NULL [-Werror=address]
     MULTI_HEAP_UNLOCK(&registered_heaps_write_lock);
                                             ^~
cc1: some warnings being treated as errors

**Comment by jeremyjh** [comment]
The compile error you are getting is coming from a file in ESP-IDF, it is not even getting as far as compiling this project. I'd guess your environment is setup wrong, maybe you are not using the right version of the compiler.

**Comment by Franciscopcosta** [comment]
Toolchain version: esp-2019r2
Compiler version: 8.2.0
 is it correct?

**Comment by Franciscopcosta** [comment]
SOLVED here:
https://github.com/espressif/esp-idf/pull/4597
