### ISSUE TITLE
C++ Support - tftspi.h missing extern "C" macros

### ISSUE THREAD

**Issue by JMare** [jeremyjh/ESP32_TFT_library#7]
Pretty much all in the title:
While tft.h has extern c macros to allow calling from c++ main components, tftspi.h needs these tags so that TFT_PinsInit() and TFT_display_init() can be called from a project compiled as c++.

**Comment by jeremyjh** [comment]
You don't need to include tftspi.h directly. [tft.h includes](https://github.com/jeremyjh/ESP32_TFT_library/blob/master/components/tft/tft.h#L16) it inside the extern block. So you only need to include tft.h in your application and it will work fine. I used this library in a C++ project.

**Comment by JMare** [comment]
Ahh, got it, that did the trick!
Thank you, closing this now.
