### ISSUE TITLE
License file request

### ISSUE THREAD

**Issue by bastianhjaeger** [jeremyjh/ESP32_TFT_library#9]
Hi @jeremyjh ,

great work you have done. This helps me a lot!

Just in case it might get relevant: Could you add a license to your repo, please?

**Comment by jeremyjh** [comment]
I can't. It is a fork of a project with no license file. I've [requested](https://github.com/loboris/ESP32_TFT_library/issues/80) loboris address this but he is not responding and he's the only person who can do so.

**Comment by bastianhjaeger** [comment]
Didn't realize this was a fork. Sorry and thanks for the reply ;)
